baseURL = 'https://vmihdal.github.io/'
languageCode = 'en-us'
title = 'vmihdal'
theme = 'hugo-coder'

defaultContentLanguage = 'en'

[params]
  author = "Volodymyr Mihdal"
  info = "Software Engineer"
  description = "Software Engineer Blog"
  keywords = "blog,developer,engineer,personal,Rust,rust"
  gravatar = "volodymyr.migdal@gmail.com"
  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/vmihdal"
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/vmigdal/"

[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
